const {getAll,insertOne,deleteOne,sort,revsort,getOne,viewall,viewone,updateOne}=require("../controller/plant_controllers.js")
const express=require('express')
const path=require('path')
const router=express.Router()
// router.route('/').get(mainFile)
router.route('/getall').get(getAll)
router.route('/insert').post(insertOne)
router.route('/delete').post(deleteOne)
router.route('/sort').get(sort)
router.route('/revsort').get(revsort)
router.route('/getOne').get(getOne)
router.route('/viewAll').get(viewall)
router.route('/viewOne').get(viewone)
router.route('/update').post(updateOne)
module.exports=router